using Core;
using Core.DB;
using Core.UnitOfWork;
using Core.Utilities;
using SmartExpress.Admin.Models;
using SmartExpress.Admin.Reusable.FilterAttributes;
using System.Web.Mvc;

namespace SmartExpress.Admin.Reusable
{
    [BeforePageLoads]
    public class BaseController : Controller
    {
        public User UserItem { get; set; }
        public IUnitOfWork UnitOfWork { get; set; }

        public BaseController()
        {
            UnitOfWork = new UnitOfWork(new DbCoreDataContext());
        }

        public void GenerateSuccessErrorMessageContainer()
        {
            var model = ViewBag.LayoutViewModel as LayoutViewModel;
            if (model != null)
            {
                if (model.SuccessErrorMessageInfo == null)
                {
                    model.SuccessErrorMessageInfo = new SuccessErrorMessageInfo();
                }
                model.SuccessErrorMessageInfo.IsContainerAutoGenerated = true;

            }
            ViewBag.LayoutViewModel = model;
        }

        public ActionResult NotFound()
        {
            return View("NotFound");
        }

        public void InitErrorMessage(string message)
        {
            Session["ErrorMessage"] = message;
        }

        public void InitSuccessMessage(string message)
        {
            Session["SuccessMessage"] = message;

        }

    }

    public class BaseViewModel
    {
        public IUnitOfWork UnitOfWork { get; set; }

        public BaseViewModel()
        {
            UnitOfWork = new UnitOfWork(new DbCoreDataContext());
        }
    }
}